"""create initial tables

Revision ID: 7d0f808060db
Revises:
Create Date: 2026-09-04 00:31:06.887142

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7d0f808060db"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exhibitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "end_date IS NULL or start_date IS NULL or end_date >= start_date",
            name="ck_exhibitions_valid_date_range",
        ),
        sa.CheckConstraint(
            "length(trim(description)) > 0", name="ck_exhibitions_description_not_blank"
        ),
        sa.CheckConstraint(
            "length(trim(title)) > 0", name="ck_exhibitions_title_not_blank"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_exhibitions_is_active", "exhibitions", ["is_active"], unique=False
    )
    op.create_table(
        "works",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("exhibition_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("artist", sa.String(length=150), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("audio_url", sa.Text(), nullable=True),
        sa.Column("audio_description_url", sa.Text(), nullable=True),
        sa.Column("libras_video_url", sa.Text(), nullable=True),
        sa.Column("public_slug", sa.String(length=180), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(trim(description)) > 0", name="ck_works_description_not_blank"
        ),
        sa.CheckConstraint(
            "length(trim(public_slug)) > 0", name="ck_works_public_slug_not_blank"
        ),
        sa.CheckConstraint("length(trim(title)) > 0", name="ck_works_title_not_blank"),
        sa.ForeignKeyConstraint(
            ["exhibition_id"], ["exhibitions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_slug"),
    )
    op.create_index("ix_works_exhibition_id", "works", ["exhibition_id"], unique=False)
    op.create_index("ix_works_is_active", "works", ["is_active"], unique=False)
    op.create_table(
        "access_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("work_id", sa.UUID(), nullable=False),
        sa.Column("accessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["work_id"], ["works.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_access_events_accessed_at", "access_events", ["accessed_at"], unique=False
    )
    op.create_index(
        "ix_access_events_work_id_accessed_at",
        "access_events",
        ["work_id", "accessed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_access_events_work_id_accessed_at", table_name="access_events")
    op.drop_index("ix_access_events_accessed_at", table_name="access_events")
    op.drop_table("access_events")
    op.drop_index("ix_works_is_active", table_name="works")
    op.drop_index("ix_works_exhibition_id", table_name="works")
    op.drop_table("works")
    op.drop_index("ix_exhibitions_is_active", table_name="exhibitions")
    op.drop_table("exhibitions")
    # ### end Alembic commands ###
